2021-10-30 00:43:48.557 +02:00 [Information] [] Starting web host.
2021-10-30 01:08:26.495 +02:00 [Information] [] Starting web host.
2021-10-30 01:08:33.296 +02:00 [Information] [] Application started. Press Ctrl+C to shut down.
2021-10-30 01:08:33.300 +02:00 [Information] [] Hosting environment: "Development"
2021-10-30 01:08:33.301 +02:00 [Information] [] Content root path: "F:\VSProjects\OnlineAuction\Onlineauction.API"
2021-10-30 01:08:38.766 +02:00 [Error] [80000002-0003-fd00-b63f-84710c7967bb] An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: Failed to proxy the request to http://localhost:4200/, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:4200/.

The underlying exception message was 'Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot.'.Check the InnerException for more details.
 ---> System.Net.Http.HttpRequestException: Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot.
 ---> System.Net.Sockets.SocketException (10061): Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-10-30 01:08:59.102 +02:00 [Information] [] Starting web host.
2021-10-30 01:09:00.880 +02:00 [Information] [] Application started. Press Ctrl+C to shut down.
2021-10-30 01:09:00.884 +02:00 [Information] [] Hosting environment: "Development"
2021-10-30 01:09:00.885 +02:00 [Information] [] Content root path: "F:\VSProjects\OnlineAuction\Onlineauction.API"
2021-10-30 01:13:33.887 +02:00 [Information] [] Starting web host.
2021-10-30 01:13:35.647 +02:00 [Information] [] Application started. Press Ctrl+C to shut down.
2021-10-30 01:13:35.650 +02:00 [Information] [] Hosting environment: "Development"
2021-10-30 01:13:35.651 +02:00 [Information] [] Content root path: "F:\VSProjects\OnlineAuction\Onlineauction.API"
